{% set version = "0.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-olsrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/olsrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/olsrr/olsrr_{{ version }}.tar.gz
  sha256: e97298d8b640c61ea0cc3193a29011ea8dad3c2953b76bcda896afb0d4447f43

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-car
    - r-ggplot2
    - r-goftest
    - r-gridextra
    - r-nortest
    - r-xplorerr
  run:
    - r-base
    - r-car
    - r-ggplot2
    - r-goftest
    - r-gridextra
    - r-nortest
    - r-xplorerr

test:
  commands:
    - $R -e "library('olsrr')"           # [not win]
    - "\"%R%\" -e \"library('olsrr')\""  # [win]

about:
  home: https://olsrr.rsquaredacademy.com/
  dev_url: https://github.com/rsquaredacademy/olsrr
  license: MIT
  summary: Tools designed to make it easier for users, particularly beginner/intermediate R users to build ordinary least squares regression models. Includes comprehensive regression output, heteroskedasticity tests, collinearity diagnostics, residual diagnostics, measures of influence, model fit assessment and variable
    selection procedures.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - comatrion
