{% set version = "0.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-olsrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/olsrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/olsrr/olsrr_{{ version }}.tar.gz
  sha256: e97298d8b640c61ea0cc3193a29011ea8dad3c2953b76bcda896afb0d4447f43

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-car
    - r-data.table
    - r-ggplot2
    - r-goftest
    - r-gridextra
    - r-nortest
  run:
    - r-base
    - r-rcpp
    - r-car
    - r-data.table
    - r-ggplot2
    - r-goftest
    - r-gridextra
    - r-nortest

test:
  commands:
    - $R -e "library('olsrr')"           # [not win]
    - "\"%R%\" -e \"library('olsrr')\""  # [win]

about:
  home: https://olsrr.rsquaredacademy.com/, https://github.com/rsquaredacademy/olsrr
  license: MIT
  summary: Tools designed to make it easier for users, particularly beginner/intermediate R users to build ordinary least squares regression models. Includes comprehensive regression output, heteroskedasticity tests, collinearity diagnostics, residual diagnostics, measures of influence, model fit assessment and variable
    selection procedures.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - comatrion

# Package: olsrr
# Type: Package
# Title: Tools for Building OLS Regression Models
# Version: 0.5.3
# Authors@R: person("Aravind", "Hebbali", email = "hebbali.aravind@gmail.com", role = c("aut", "cre"))
# Description: Tools designed to make it easier for users, particularly beginner/intermediate R users to build ordinary least squares regression models. Includes comprehensive regression output, heteroskedasticity tests, collinearity diagnostics, residual diagnostics, measures of influence, model fit assessment and variable selection procedures.
# Depends: R(>= 3.3)
# Imports: car, data.table, ggplot2, goftest, graphics, gridExtra, nortest, Rcpp, stats, utils
# Suggests: covr, descriptr, knitr, rmarkdown, testthat, vdiffr, xplorerr
# License: MIT + file LICENSE
# URL: https://olsrr.rsquaredacademy.com/, https://github.com/rsquaredacademy/olsrr
# BugReports: https://github.com/rsquaredacademy/olsrr/issues
# Encoding: UTF-8
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2020-02-10 11:05:37 UTC; HP
# Author: Aravind Hebbali [aut, cre]
# Maintainer: Aravind Hebbali <hebbali.aravind@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-02-10 12:00:02 UTC
